### ISSUE TITLE
connect application form frontend to backend

### ISSUE THREAD

**Issue by karenm08** [BCIT-SSD-2020-21/industry-project-checkmarks#113]

**Comment by tiQu** [comment]
Hey there. Let's look at each step of the trademark application process based on the code so we can replicate what is happening with the revised front-end:

1. PaymentConfirmation.js (front-end):
This file handles all three steps at the end of the application process. Here's the order / structure in which statements are called:
```
sendPayment(
    createEmail(
        createClioContact)
    )
)
```
First, `sendPayment()` send a **POST** request to the server's **PaymentController.cs**. In the body of the request we have:
- payment amount (string)
- method (string, which is a value called id that is being returned from the Payment API in **PaymentForm.js**, which comes from AffiniPay (their chosen payment solution for handling the credit card payments)
- account_id (string, hard-coded)

2. PaymentController.cs (back-end)
This controller takes the entire JSON object from the front-end and sends it in a **POST** request to **chargio**, with an auth token in the header. 

3. PaymentConfiguration.js (front-end)
Here, `sendEmail()` triggers another **POST** to EmailController.cs in the back-end. The body of this request has all details the user entered in the previous form pages (first name, last name, address), minus payment info.

4. EmailController.cs (back-end)
The controller takes the JSON body and builds a summary email to be sent from our industry client's email account to the user's address, with file attachments for any logos that were uploaded. Note that when an email is sent this way, old uploaded images on the server are deleted.

5. PaymentConfirmation.js (front-end)
Within `sendEmail()`, another function is triggered: `createClioContact()`. This is a **POST** request with the user's info to the **ClioController** in the back-end. 

6. ClioController.cs (back-end)
This controller creates a new Clio contact with the provided information, sending a **POST** request to the **Clio URL** in **appsettings.json** with an authentication token.

If successful, Clio returns a contact object that is parsed into a **Matter** object in C#. The **Matter** object has the user's information as well as a hard-coded description ("Checkmarks.ca trademark registration"). 

This **Matter** object is sent via **POST** to a Clio-specific **MattersUrl**. 

7. PaymentConfirmation.js (front-end)
Back in the client, if all of this was successful, the user is directed to the **Success** component.
