### ISSUE TITLE
(ongoing) assess copy needed for website

### ISSUE THREAD

**Issue by tiQu** [BCIT-SSD-2020-21/industry-project-checkmarks#117]
We need to keep a list of texts that we need for the different website pages (about me, pricing, etc.). Basically, everything that our client Justin needs to make decisions on: for example, what should the prices be for the three tiers and what services should they include? What questions and answers should go in the frequently asked questions section (FAQ)? We'll start the conversation here on GitHub and update the list as needed.

**Comment by tiQu** [comment]
Hi @fatmabadri , here's the list from Slack--please keep adding more areas / texts as the front-end is being built. Thank you!!

**About us**
**FAQ answers:**
- What is a trademark?
- What is the difference between a trade name and a trademark?
- Why should I care about search and review services?
- How do trademark lawyers or IP agents help?
- Do I need a lawyer to trademark?
- Why should I care about search and review services?
**Pricing tiers (current version has three); for each of these:**
- Tier name
- Tier features
- Tier price
**Terms as final piece of the application form**

**Comment by fatmabadri** [comment]
An email has been sent to the project owner.

**Comment by fatmabadri** [comment]
Web content has been provided
